import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-cover min-h-screen flex justify-center items-start bg-sky-300 bg-blend-overlay py-7 px-4">
        {children}
      </body>
    </html>
  );
}
